//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKS_Sys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public System.Guid AttendanceID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<System.Guid> AttSetID { get; set; }
        public Nullable<System.DateTime> SignTime { get; set; }
        public Nullable<int> State { get; set; }
        public string Message { get; set; }
        public string Location { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<bool> AttSetType { get; set; }
        public string TypeName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsDelete { get; set; }
    }
}
