//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKS_Sys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceMsgAlert
    {
        public System.Guid MsgID { get; set; }
        public System.Guid UserID { get; set; }
        public System.DateTime AlertDate { get; set; }
        public string Message { get; set; }
        public int AttType { get; set; }
        public bool IsDelete { get; set; }
    }
}
