//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKS_Sys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceSet
    {
        public System.Guid AttSetID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string TypeName { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> Endtime { get; set; }
        public Nullable<bool> AttSetType { get; set; }
        public Nullable<bool> UserTyep { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public bool IsDelete { get; set; }
    }
}
