//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKS_Sys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormControl
    {
        public System.Guid ControlID { get; set; }
        public string ControlName { get; set; }
        public System.Guid FormID { get; set; }
        public System.Guid LayoutID { get; set; }
        public int PositionNo { get; set; }
        public bool IsRequired { get; set; }
        public bool IsFieldTotal { get; set; }
        public int ControlType { get; set; }
        public string Remark { get; set; }
        public string TabelName { get; set; }
        public string FieldName { get; set; }
    }
}
