//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKS_Sys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormCategory
    {
        public FormCategory()
        {
            this.FormInfo = new HashSet<FormInfo>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public int FormNumber { get; set; }
    
        public virtual ICollection<FormInfo> FormInfo { get; set; }
    }
}
