//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKS_Sys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationSetting
    {
        public System.Guid LocalSetID { get; set; }
        public string LocationDeclare { get; set; }
        public string LocationStartTime { get; set; }
        public string LocationEndTime { get; set; }
        public Nullable<int> LocationSource { get; set; }
        public Nullable<int> Freqency { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsDelete { get; set; }
    }
}
