//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKS_Sys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.WorkFlowEntrust = new HashSet<WorkFlowEntrust>();
            this.WorkFlowEntrust1 = new HashSet<WorkFlowEntrust>();
            this.WorkFlowProcess = new HashSet<WorkFlowProcess>();
            this.WorkFlowRun = new HashSet<WorkFlowRun>();
            this.WorkFlowRunProc = new HashSet<WorkFlowRunProc>();
            this.WorkFlowRunProc1 = new HashSet<WorkFlowRunProc>();
        }
    
        public System.Guid UserID { get; set; }
        public System.Guid Token { get; set; }
        public string JPushID { get; set; }
        public string UserName { get; set; }
        public string LoginNumber { get; set; }
        public string Password { get; set; }
        public string UserImg { get; set; }
        public bool State { get; set; }
        public Nullable<int> SortNo { get; set; }
        public bool IsLeader { get; set; }
        public string ChipName { get; set; }
        public string IMSI1 { get; set; }
        public string IMSI2 { get; set; }
        public string IMEI1 { get; set; }
        public bool IMSI1Bind { get; set; }
        public bool IMSI2Bind { get; set; }
        public bool IMEI1Bind { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual ICollection<WorkFlowEntrust> WorkFlowEntrust { get; set; }
        public virtual ICollection<WorkFlowEntrust> WorkFlowEntrust1 { get; set; }
        public virtual ICollection<WorkFlowProcess> WorkFlowProcess { get; set; }
        public virtual ICollection<WorkFlowRun> WorkFlowRun { get; set; }
        public virtual ICollection<WorkFlowRunProc> WorkFlowRunProc { get; set; }
        public virtual ICollection<WorkFlowRunProc> WorkFlowRunProc1 { get; set; }
    }
}
