//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKS_Sys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRelation
    {
        public System.Guid RelationID { get; set; }
        public Nullable<System.Guid> DeptPostID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public bool Type { get; set; }
        public bool IsDelete { get; set; }
    }
}
