//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKS_Sys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFlowRun
    {
        public WorkFlowRun()
        {
            this.WorkFlowAnnex = new HashSet<WorkFlowAnnex>();
            this.WorkFlowRunProc = new HashSet<WorkFlowRunProc>();
        }
    
        public System.Guid RunID { get; set; }
        public string RunName { get; set; }
        public System.Guid FormID { get; set; }
        public System.Guid FlowID { get; set; }
        public System.Guid UserID { get; set; }
        public int CompleteNumber { get; set; }
        public int NndoneNumber { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual FormInfo FormInfo { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<WorkFlowAnnex> WorkFlowAnnex { get; set; }
        public virtual WorkFlowInfo WorkFlowInfo { get; set; }
        public virtual ICollection<WorkFlowRunProc> WorkFlowRunProc { get; set; }
    }
}
